# fly.toml app configuration file generated for lively-morning-6507 on 2023-09-23T12:49:59+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lively-morning-6507"
primary_region = "arn"

[deploy]
  release_command = "npm run build"

[processes]
  app = "node app.js"

[build]
  [build.args]
    NODE_VERSION = "16.20.2"

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

 [[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"
