name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    env:
      ACTOR: ${{ github.actor }}
      REPOSITORY: ${{ github.repository }}
      COMMIT_SHA: ${{ github.sha }}
      COMMIT_URL: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}
    steps:
      - uses: actions/checkout@v3
      - name: deployment url
        run:
          echo "DEPLOYMENT_URL=https://$(cat fly.toml | grep '^app = "' | cut -d'"' -f 2).fly.dev" >> $GITHUB_ENV
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
        if: ${{ !env.ACT }}   # skipped when run using nektos/act since the default medium image does not contain xvfb which is required by cypress
      - name: Deploy
        id: deploy
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        if: ${{ github.event_name == 'push' && !env.ACT }}
      - name: Notify when a new version is deployed
        if: ${{ steps.deploy.outcome == 'success' }}
        uses: rjstone/discord-webhook-notify@89b0bf43c2c8514f70d0dcba4a706b904e8a3112   # (v1.0.4)
        with:
          severity: info
          avatarUrl: https://github.githubassets.com/images/modules/logos_page/Octocat.png
          description: At ${{ env.DEPLOYMENT_URL }} by ${{ env.ACTOR }}.
          text: A new version of ${{ env.REPOSITORY }} deployed.
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Notify when a build fails
        if: ${{ failure() }}
        uses: rjstone/discord-webhook-notify@89b0bf43c2c8514f70d0dcba4a706b904e8a3112   # (v1.0.4)
        with:
          severity: error
          avatarUrl: https://github.githubassets.com/images/modules/logos_page/Octocat.png
          description: Commit [${{ env.COMMIT_SHA }}](${{ env.COMMIT_URL }}) by ${{ env.ACTOR }}.
          text: ${{ env.REPOSITORY }} build failed.
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@a2c70ae13a881faf2b4953baaa9e49731997ab36   # (v1.67.0)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          DRY_RUN: false
        if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
